# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage
rvm: 2.2.2
language: objective-c
osx_image: xcode 11
notifications:
  slack: azuritul:lCn25gPPuWbKQ4VlfG5Qglwp

# cache: cocoapods
# podfile: Example/Podfile
podfile: Example/Podfile
before_install:
 - gem install xcpretty
 - gem install cocoapods
 - pod setup

script:
- set -o pipefail && xcodebuild test -workspace Example/AZExpandableIconListView.xcworkspace -scheme AZExpandableIconListView-Example -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.1' ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint

